stackADTclient: stackADTclient.o stackADT.o
	gcc -o stackADTclient stackADTclient.o stackADT.o
	
stackADTclient.o: stackADTclient.c stackADT.h
	gcc -c stackADTclient.c stackADT.h
	
stackADT.o: stackADT.c stackADT.h
	gcc -c stackADT.c stackADT.h
	
	
